<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAP-2441" failures="2" tests="2" name="Surefire test" time="3.232" errors="0" timestamp="2024-07-20T09:34:05 IST">
  <testcase classname="com.pilvo.automation.OpenWeatherTest" name="testGetWeatherData" time="2.261">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.pilvo.automation.OpenWeatherTest.testGetWeatherData(OpenWeatherTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetWeatherData -->
  <testcase classname="com.pilvo.automation.plivoTest" name="testSendSMS" time="0.937">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.pilvo.automation.plivoTest.testSendSMS(plivoTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testSendSMS -->
</testsuite> <!-- Surefire test -->
